# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(blank=True, max_length=500, null=True)),
                ('glass', models.CharField(blank=True, max_length=500, null=True)),
                ('blend', models.CharField(blank=True, max_length=500, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuboard.Board')),
            ],
            options={
                'db_table': 'cocktail',
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('quantite_type', models.CharField(blank=True, max_length=500, null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuboard.Cocktail')),
            ],
            options={
                'db_table': 'cocktail_ingredient',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(blank=True, max_length=500, null=True)),
                ('ordre', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'instruction',
            },
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='menuboard.CocktailIngredient', to='menuboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='instructions',
            field=models.ManyToManyField(to='menuboard.Instruction'),
        ),
    ]
